### ISSUE TITLE
Formatting for "Upload Level CHK" is messed up

### ISSUE THREAD

**Issue by AndreNIH** [gd-programming/gddocs#15]
![chrome_oVKpxtXnQW](https://user-images.githubusercontent.com/31828626/80674255-32b15080-8a66-11ea-94bb-eb7195e1346d.png)

**Comment by Altenhh** [comment]
I believe this issue can be found [here](https://github.com/gd-programming/gddocs/blob/master/docs/topics/encryption/chk.md)

```md
### **pseudocode** ###
```

The three hashtags at the end should be removed.

**Comment by SMJSGaming** [comment]
honestly, didn't see the issue but just noticed that mistake
