### ISSUE TITLE
Add document about getGJLevelScores211.php

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [gd-programming/gddocs#33]
s1: attempts - 8354
s7: randomSeed
s9: coins you got - 5819

I dont't know s2-s6 and s8

**Comment by WOSHIZHAZHA120** [comment]
and s5, s8 is variable.

**Comment by NeKitDS** [comment]
`-`? You ADD those numbers sometimes. I do have a list of those though, let me find it

**Comment by NeKitDS** [comment]
s1 = attempts + 8354
s2 = jumps + 3991
s3 = seconds + 4085
s4 = 1482 * 2 + (jumps + 3991) * (percentage + 8354) + ((seconds + 4085) ** 2) - 50028039
s4 is 1482 if jumps, percentage and seconds are 0
random number (somewhere in range [1000, 10000])
s5 = unknown
s6 = random seed
s7 = attempts
s8 = coins + 5819
s9 = timely ID
s10 = chk

**Comment by NeKitDS** [comment]
Not sure about s10, tbh.

**Comment by NeKitDS** [comment]
Alright, I have adjusted the numbers. Would be cool if anyone figured out what `s6` is, though it isn't even middle priority at this point.

**Comment by WOSHIZHAZHA120** [comment]
> s1 = attempts + 8354
> s2 = jumps + 3991
> s3 = seconds + 4085
> s4 = 1482 * 2 + (jumps + 3991) * (percentage + 8354) + ((seconds + 4085) ** 2) - 50028039
> s4 is 1482 if jumps, percentage and seconds are 0
> s5 = random number (somewhere in range [1000, 10000])
> s6 = unknown
> s7 = random seed (rs)
> s8 = attempts
> s9 = coins + 5819
> s10 = timely ID

s4 = 1482 * (hasPlayed + 1) + (jumps + 3991) * (percentage + 8354) + ((seconds + 4085) ** 2) - 50028039

**Comment by WOSHIZHAZHA120** [comment]
> Alright, I have adjusted the numbers. Would be cool if anyone figured out what `s6` is, though it isn't even middle priority at this point.

s6 value like ```AA==``` but I don't know how this mean.
