### ISSUE TITLE
Uh oh, you did a fucky wucky

### ISSUE THREAD

**Issue by willycoffee** [gd-programming/gddocs#40]
A error that occurs when visiting the [gamesave](http://docs.gdprogra.me/#/resources/client/gamesave) part of the site.

Error:
```
Uh oh, you did a fucky wucky
Wonder how you got here. Maybe an invalid link?

I'd suggest reporting about it to the team as best as you can.
```

**Comment by Cos8o** [comment]
Website never worked in the first place; an update is coming soon.
