### ISSUE TITLE
I'm fucking lucky

### ISSUE THREAD

**Issue by ForeverGD** [gd-programming/gddocs#44]
![Screenshot_20201224-131256](https://user-images.githubusercontent.com/69404872/103085310-655e1980-45f2-11eb-8c25-13b51e62eb65.jpg)

What

**Comment by kyurime** [comment]
Congrats on your good fortune! May you please provide the URL of the page you were accessing when you found this error?

**Comment by ForeverGD** [comment]
> Поздравляю с удачей! Не могли бы вы предоставить URL-адрес страницы, на которую вы заходили, когда обнаружили эту ошибку?

http://docs.gdprogra.me/#/resources/client/gamesave
