### ISSUE TITLE
Add documentation for endpoints

### ISSUE THREAD

**Issue by ghost** [gd-programming/gddocs#6]
Properly add endpoints and what they do to the documentation.

**Comment by GDColon** [comment]
I nominate @SMJSGaming to do the honors

**Comment by Homurasama** [comment]
No.

**Comment by GDColon** [comment]
![image](https://user-images.githubusercontent.com/56617416/80543569-27cec100-897d-11ea-9eea-402665f05538.png)

**Comment by Altenhh** [comment]
This issue is already assigned to @Homurasama.

**Comment by SMJSGaming** [comment]
honestly idc how far you are @GDColon, you basically with brute force just took away this issue while she was working on this

**Comment by NeKitDS** [comment]
Hey, since no one seems to be working on this one, may I work on it?

**Comment by nekitdev** [comment]
Closed by #41
